### ISSUE TITLE
Permission denied (publickey) issue

### ISSUE THREAD

**Issue by erikderzweite** [konstruktoid/SSHD_Build#2]
I'm starting the image with docker-compose, like this:
```
  ssh:
    container_name: ssh
    image: konstruktoid/openssh-server:latest
    restart: always
    labels:
      - "traefik.enable=false"
    ports:
      - "22:22"
    volumes:
      - /docker/ssh/config/:/etc/ssh/
      - /docker/ssh/home/:/home/
      - /docker/ssh/passwd:/etc/passwd
      - /docker/ssh/shadow:/etc/shadow
    networks:
      - web
```
I have copied passwd and shadow file from my host system as well as the /etc/ssh/ and /home/*/.ssh folders to /docker/ssh as shown in the docker-compose config. I want to login via publickeys, but when I try to ssh user@server.tld -p 22 I get "Permission denied (publickey)."

On the host system I have set up the port to 2222 and ssh user@server.tld -p 2222 works.

Any ideas?
